// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrJNst35fQbfISww1BuYMwFA31kYLKjKg',
    appId: '1:160514718786:web:29c4557a06ed5b7514c1db',
    messagingSenderId: '160514718786',
    projectId: 'pawsafe-becdf',
    authDomain: 'pawsafe-becdf.firebaseapp.com',
    storageBucket: 'pawsafe-becdf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALxNRZBtszDRGWatD5j3bFQ--ggX5gitY',
    appId: '1:160514718786:android:9c701606e58e491c14c1db',
    messagingSenderId: '160514718786',
    projectId: 'pawsafe-becdf',
    storageBucket: 'pawsafe-becdf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjpoVgl9lEUmeUb0OWWXYIZW0gRfNxYds',
    appId: '1:160514718786:ios:9bb153bab275d9d814c1db',
    messagingSenderId: '160514718786',
    projectId: 'pawsafe-becdf',
    storageBucket: 'pawsafe-becdf.firebasestorage.app',
    iosBundleId: 'com.example.pawsafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjpoVgl9lEUmeUb0OWWXYIZW0gRfNxYds',
    appId: '1:160514718786:ios:9bb153bab275d9d814c1db',
    messagingSenderId: '160514718786',
    projectId: 'pawsafe-becdf',
    storageBucket: 'pawsafe-becdf.firebasestorage.app',
    iosBundleId: 'com.example.pawsafe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrJNst35fQbfISww1BuYMwFA31kYLKjKg',
    appId: '1:160514718786:web:30154f93b7e38af314c1db',
    messagingSenderId: '160514718786',
    projectId: 'pawsafe-becdf',
    authDomain: 'pawsafe-becdf.firebaseapp.com',
    storageBucket: 'pawsafe-becdf.firebasestorage.app',
  );
}
